-- Milestone 2 --
-- Aaron Pollack | Chelsea Thompson --

-- DROP ALL EXISTING TABLES IN CORRECT ORDER TO CLEAR DB--------

DROP TABLE IF EXISTS TEST;
DROP TABLE IF EXISTS TEST_TYPE;
DROP TABLE IF EXISTS EMPLOYMENT_HISTORY;
DROP TABLE IF EXISTS EMPLOYER;
DROP TABLE IF EXISTS DEGREE_EARNED;
DROP TABLE IF EXISTS PAST_INSTITUION;
DROP TABLE IF EXISTS APPLICATION;
DROP TABLE IF EXISTS MAJOR;
DROP TABLE IF EXISTS COLLEGE;
DROP TABLE IF EXISTS STUDENT_TYPE;
DROP TABLE IF EXISTS DEGREE_TYPE;
DROP TABLE IF EXISTS TERM;
DROP TABLE IF EXISTS APPLICANT_RACE;
DROP TABLE IF EXISTS RACE;
DROP TABLE IF EXISTS MILITARY_STATUS;
DROP TABLE IF EXISTS MIL_BRANCH_TYPE;
DROP TABLE IF EXISTS MIL_STATUS_TYPE;
DROP TABLE IF EXISTS APPLICANT;
DROP TABLE IF EXISTS ADDRESS;
DROP TABLE IF EXISTS STATE;
DROP TABLE IF EXISTS COUNTRY;
DROP TABLE IF EXISTS GENDER;

--- CREATE TABLES --------

CREATE TABLE STATE(
  STATE_ID INT PRIMARY KEY NOT NULL,
  STATE_NAME VARCHAR ( 30 ) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE COUNTRY(
  COUNTRY_ID CHAR(2) PRIMARY KEY NOT NULL,
  COUNTRY_NAME VARCHAR ( 30 ) NOT NULL
) ENGINE=InnoDB;

----- CREATE TABLE WITH FOREIGN KEY -------
----- USE `ON UPDATE CASCADE` for referential integrity -----
----- ASSUME 30 CHAR ENOUGH FOR ADDRESS LINE 1 -------

CREATE TABLE ADDRESS(
  ADDRESS_ID INT NOT NULL PRIMARY KEY,
  LINE_1 VARCHAR ( 30 ) NOT NULL,
  LINE_2 VARCHAR ( 30 ),
  CITY VARCHAR ( 30 ) NOT NULL,
  STATE_ID INT,
  FOREIGN KEY ( STATE_ID ) REFERENCES STATE ( STATE_ID ) ON UPDATE CASCADE,
  ZIP_CODE VARCHAR ( 7 ) NOT NULL,
  COUNTRY_ID CHAR(2),
  FOREIGN KEY ( COUNTRY_ID ) REFERENCES COUNTRY ( COUNTRY_ID ) ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE GENDER(
  GENDER_ID INT NOT NULL PRIMARY KEY,
  GENDER_TYPE VARCHAR ( 5 ) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE LOGIN(
  EMAIL VARCHAR(100) NOT NULL PRIMARY KEY,
  PASSWORD VARCHAR(100) NOT NULL
) ENGINE=InnoDB;

----- ASSUME 30 CHAR ENOUGH FOR FIRST AND LAST NAME ------

CREATE TABLE APPLICANT(
  APPLICANT_ID INT NOT NULL PRIMARY KEY,
  EMAIL VARCHAR(100) NOT NULL,
  FOREIGN KEY ( EMAIL ) REFERENCES LOGIN ( EMAIL ) ON DELETE CASCADE,
  ADDRESS_ID INT NOT NULL,
  FOREIGN KEY ( ADDRESS_ID ) REFERENCES ADDRESS ( ADDRESS_ID ) ON UPDATE CASCADE,
  FIRST_NAME VARCHAR ( 30 ) NOT NULL,
  LAST_NAME VARCHAR ( 30 ) NOT NULL,
  PREFERRED_NAME VARCHAR ( 30 ),
  DOB DATE NOT NULL,
  PHONE_AREA_CODE CHAR ( 3 ) NOT NULL,
  PHONE_LAST_SEVEN CHAR ( 7 ) NOT NULL,
  US_CITIZEN BOOLEAN NOT NULL,
  NATIVE_LANGUAGE BOOLEAN NOT NULL,
  GENDER_ID INT NOT NULL,
  FOREIGN KEY ( GENDER_ID ) REFERENCES GENDER ( GENDER_ID ) ON UPDATE CASCADE,
  HISP_LATINO BOOLEAN NOT NULL
) ENGINE=InnoDB;

CREATE TABLE EMPLOYER(
  EMPLOYER_ID INT NOT NULL PRIMARY KEY,
  ADDRESS_ID INT NOT NULL,
  FOREIGN KEY ( ADDRESS_ID ) REFERENCES ADDRESS ( ADDRESS_ID) ON UPDATE CASCADE,
  PHONE_AREA_CODE CHAR( 3 ) NOT NULL,
  PHONE_LAST_SEVEN CHAR( 7 ) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE RACE(
  RACE_CODE INT NOT NULL PRIMARY KEY,
  RACE_NAME VARCHAR ( 32 ) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE TERM(
  TERM_ID INT NOT NULL PRIMARY KEY,
  QUARTER VARCHAR ( 7 ) NOT NULL,
  YEAR VARCHAR ( 4 ) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE TEST_TYPE(
  TEST_TYPE_ID INT NOT NULL PRIMARY KEY,
  TEST_NAME VARCHAR( 30 )
) ENGINE=InnoDB;

CREATE TABLE MIL_STATUS_TYPE(
  STATUS_CODE INT NOT NULL PRIMARY KEY,
  STATUS_NAME VARCHAR ( 17 )
) ENGINE=InnoDB;

CREATE TABLE MIL_BRANCH_TYPE(
  BRANCH_CODE INT NOT NULL PRIMARY KEY,
  BRANCH_NAME VARCHAR ( 11 )
) ENGINE=InnoDB;

CREATE TABLE MILITARY_STATUS(
  APPLICANT_ID INT NOT NULL PRIMARY KEY,
  FOREIGN KEY ( APPLICANT_ID ) REFERENCES APPLICANT ( APPLICANT_ID ) ON UPDATE CASCADE,
  STATUS_CODE INT NOT NULL,
  FOREIGN KEY ( STATUS_CODE ) REFERENCES MIL_STATUS_TYPE ( STATUS_CODE ) ON UPDATE CASCADE,
  BRANCH_CODE INT NOT NULL,
  FOREIGN KEY ( BRANCH_CODE ) REFERENCES MIL_BRANCH_TYPE ( BRANCH_CODE ) ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE COLLEGE(
  COLLEGE_ID INT NOT NULL PRIMARY KEY,
  COLLEGE_NAME VARCHAR ( 50 ) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE MAJOR(
  MAJOR_ID INT NOT NULL PRIMARY KEY,
  COLLEGE_ID INT NOT NULL,
  FOREIGN KEY ( COLLEGE_ID ) REFERENCES COLLEGE ( COLLEGE_ID ) ON UPDATE CASCADE,
  MAJOR_NAME VARCHAR ( 100 ) NOT NULL
) ENGINE=InnoDB;
CREATE TABLE DEGREE_TYPE(
  DEGREE_TYPE_ID INT NOT NULL PRIMARY KEY,
  DEGREE_TYPE_NAME VARCHAR ( 30 ) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE STUDENT_TYPE(
  STUDENT_TYPE_ID INT NOT NULL PRIMARY KEY,
  STUDENT_TYPE_NAME VARCHAR ( 30 )
) ENGINE=InnoDB;

CREATE TABLE APPLICATION(
  APP_ID INT NOT NULL PRIMARY KEY,
  APPLICANT_ID INT NOT NULL,
  FOREIGN KEY ( APPLICANT_ID ) REFERENCES APPLICANT( APPLICANT_ID ) ON UPDATE CASCADE,
  MAJOR_ID INT NOT NULL,
  FOREIGN KEY ( MAJOR_ID ) REFERENCES MAJOR ( MAJOR_ID ),
  STUDENT_TYPE_ID INT NOT NULL,
  FOREIGN KEY (STUDENT_TYPE_ID) REFERENCES STUDENT_TYPE (STUDENT_TYPE_ID) ON UPDATE CASCADE,
  ACADEMIC_PROBATION BOOLEAN NOT NULL,
  DEGREE_TYPE_ID INT NOT NULL,
  FOREIGN KEY ( DEGREE_TYPE_ID ) REFERENCES DEGREE_TYPE ( DEGREE_TYPE_ID ) ON UPDATE CASCADE,
  TERM_ID INT NOT NULL,
  FOREIGN KEY ( TERM_ID ) REFERENCES TERM ( TERM_ID ),
  FINANCIAL_AID BOOLEAN NOT NULL,
  EMP_TUITION_ASSISTANCE BOOLEAN NOT NULL,
  OTHER_PROGRAMS BOOLEAN NOT NULL,
  FELON_MISDEMEAN BOOLEAN NOT NULL
) ENGINE=InnoDB;

CREATE TABLE PAST_INSTITUION(
  INSTITUTION_ID INT NOT NULL PRIMARY KEY,
  APP_ID INT NOT NULL,
  FOREIGN KEY ( APP_ID ) REFERENCES APPLICATION ( APP_ID ) ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE DEGREE_EARNED(
  DEGREE_ID INT NOT NULL PRIMARY KEY,
  INSTITUTION_ID INT NOT NULL,
  FOREIGN KEY ( INSTITUTION_ID ) REFERENCES PAST_INSTITUION ( INSTITUTION_ID) ON UPDATE CASCADE,
  DEGREE VARCHAR ( 30 ) NOT NULL,
  MAJOR VARCHAR ( 30 ) NOT NULL,
  DATE_RECEIVED DATE NOT NULL
) ENGINE=InnoDB;

CREATE TABLE EMPLOYMENT_HISTORY(
  EMPLOY_HIST_ID INT NOT NULL PRIMARY KEY,
  APP_ID INT NOT NULL,
  FOREIGN KEY ( APP_ID ) REFERENCES APPLICATION ( APP_ID ) ON UPDATE CASCADE,
  EMPLOYER_ID INT NOT NULL,
  FOREIGN KEY ( EMPLOYER_ID ) REFERENCES EMPLOYER ( EMPLOYER_ID ) ON UPDATE CASCADE,
  TITLE VARCHAR ( 30 ) NOT NULL,
  CURRENT BOOLEAN NOT NULL,
  START_DATE DATE NOT NULL,
  END_DATE DATE NOT NULL,
  FTE_STATUS BOOLEAN NOT NULL
) ENGINE=InnoDB;

CREATE TABLE APPLICANT_RACE(
  APPLICANT_ID INT NOT NULL,
  FOREIGN KEY ( APPLICANT_ID ) REFERENCES APPLICANT ( APPLICANT_ID) ON UPDATE CASCADE,
  RACE_CODE INT NOT NULL,
  FOREIGN KEY ( RACE_CODE ) REFERENCES RACE ( RACE_CODE ) ON UPDATE CASCADE,
  PRIMARY KEY (APPLICANT_ID, RACE_CODE)
) ENGINE=InnoDB;

---- USE BUILT IN DATE TYPE FOR `TEST_DATE` ------

CREATE TABLE TEST(
  TEST_ID INT NOT NULL PRIMARY KEY,
  APP_ID INT NOT NULL,
  FOREIGN KEY ( APP_ID ) REFERENCES APPLICATION ( APP_ID ) ON UPDATE CASCADE,
  TEST_TYPE_ID INT NOT NULL,
  FOREIGN KEY ( TEST_TYPE_ID ) REFERENCES TEST_TYPE ( TEST_TYPE_ID ) ON UPDATE CASCADE,
  TEST_DATE DATE NOT NULL
) ENGINE=InnoDB;

------- INSERT VALUES INTO TABLE --------

INSERT INTO RACE VALUES
  (0, 'Asian'),
  (1, 'Black/African American'),
  (2, 'Native Hawaiian/Pacific Islander'),
  (3, 'Native American/Native Indian'),
  (4, 'White/Middle Eastern');

INSERT INTO TEST_TYPE VALUES
  (0, 'CBEST'),
  (1, 'GMAT'),
  (2, 'GRE General'),
  (3, 'IELTS'),
  (4, 'MAT'),
  (5, 'PRAXIS'),
  (6, 'TOEFL'),
  (7, 'WEST-B'),
  (8, 'WEST-E');

INSERT INTO MIL_BRANCH_TYPE VALUES
  (0, 'Army'),
  (1, 'Marin Corp'),
  (2, 'Navy'),
  (3, 'Air Force'),
  (4, 'Coast Gaurd');

INSERT INTO MIL_STATUS_TYPE VALUES
  (0, 'Not a veteran'),
  (1, 'Currently serving'),
  (2, 'Previously served'),
  (3, 'Current dependent');

INSERT INTO COLLEGE VALUES
    (0, 'College of Science and Engineering'),
    (1, 'Albers School of Business'),
    (2, 'College of Arts and Sciences'),
    (3, 'College of Education'),
    (4, 'College of Nursing'),
    (5, 'School of Theology and Ministry');

INSERT INTO MAJOR VALUES
    (0,1,'Certificate in Computer Science Fundamentals'),
    (1,1,'Certificate in Software Architecture and Design'),
    (2,1,'Certificate in Software Project Management');

INSERT INTO DEGREE_TYPE VALUES
    (0,'Certificate'),
    (1,'Masters');

INSERT INTO STUDENT_TYPE VALUES
    (0,'Graduate'),
    (1,'Graduate Non-Matriculated'),
    (2,'Graduate Readmission');

INSERT INTO TERM VALUES
    (0, 'Summer', '2016'),
    (1, 'Fall', '2016'),
    (2, 'Winter', '2017'),
    (3, 'Spring', '2017');
